### ISSUE TITLE
error in chat_completion.py

### ISSUE THREAD

**Issue by liushengtong** [facebookresearch/llama-recipes#154]
### System Info

![image](https://github.com/facebookresearch/llama-recipes/assets/141293711/37480f3d-6350-4a52-baa7-48fae4a83d65)
![image](https://github.com/facebookresearch/llama-recipes/assets/141293711/14200222-451d-4b6a-aa1b-0433cd6c4641)

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

After executing the following command

`python inference/chat_completion.py --model_name /home/stliu/llama-recipes/llama_7b_hf --peft_model /home/stliu/llama-recipes/llama_7b_hf_lora  --prompt_file inference/chats.json  --quantization`

the following error occurred

### Error logs

![image](https://github.com/facebookresearch/llama-recipes/assets/141293711/c27978ba-b025-421a-a4ea-740d11f8a65b)

### Expected behavior

It should be able to run normally and successfully, and the answer for chat will appear

**Comment by HamidShojanazeri** [comment]
@liushengtong thanks for opening this issue, I could repro it, it is caused as peft is not passing the[ positional args](https://github.com/huggingface/peft/blob/e06d94ddeb6c70913593740618df76908b918d66/src/peft/peft_model.py#L995). This should be fixed in this PR #158 , alternatively you could also do `model = model.merge_and_unload()` after loading the peft model in the script.
