### ISSUE TITLE
quickstart example. unable to install the7B model

### ISSUE THREAD

**Issue by Imrancham** [facebookresearch/llama-recipes#312]
When I run the installation cell 
`%%bash
pip install llama-recipes transformers datasets accelerate sentencepiece protobuf==3.20 py7zr scipy peft bitsandbytes fire torch_tb_profiler ipywidgets
TRANSFORM=`python -c "import transformers;print('/'.join(transformers.__file__.split('/')[:-1])+'/models/llama/convert_llama_weights_to_hf.py')"`
python ${TRANSFORM} --input_dir models --model_size 7B --output_dir models_hf/7B`

I get the following error:
    with open(path, "r") as f:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'models/7B/params.json'

followed by:
CalledProcessError: Command 'b'pip install llama-recipes transformers datasets accelerate sentencepiece protobuf==3.20 py7zr scipy peft bitsandbytes fire torch_tb_profiler ipywidgets\nTRANSFORM=`python -c "import transformers;print(\'/\'.join(transformers.__file__.split(\'/\')[:-1])+\'/models/llama/convert_llama_weights_to_hf.py\')"`\npython ${TRANSFORM} --input_dir models --model_size 7B --output_dir models_hf/7B\n'' returned non-zero exit status 1.

Does any one have an idea how fix this bug?

**Comment by HamidShojanazeri** [comment]
@Imrancham this notebook assume you have downloaded the checkpoints and BTW you could also instead of running the first cell to convert llama original checkpoints to HF ones, just do the installs and in the second cell "model =LlamaForCausalLM.from_pretrained(model_id, load_in_8bit=True, device_map='auto', torch_dtype=torch.float16)
" pass "meta-llama/Llama-2-7b-hf" as the model_id this way you should not need the first step, checkpoints are already in HF format. Just make sure you have logged in into your HF, `huggingface-cli login` https://huggingface.co/docs/huggingface_hub/quick-start#login

**Comment by TeddyTang11** [comment]
```
%%bash
pip install llama-recipes transformers datasets accelerate sentencepiece protobuf==3.20 py7zr scipy peft bitsandbytes fire torch_tb_profiler ipywidgets
TRANSFORM=`python -c "import transformers;print('/'.join(transformers.__file__.split('/')[:-1])+'/models/llama/convert_llama_weights_to_hf.py')"`
python ${TRANSFORM} --input_dir models --model_size 7B --output_dir models_hf/7B
```

How do I run this command on a Windows PC? anaconda prompt does not support bash scripts
